### ISSUE TITLE
The snippets don't auto select words for replacement

### ISSUE THREAD

**Issue by Telokis** [timothymclane/vscode-react-redux-snippets#7]
In your gif, I can see your cursor auto selecting `prop` for quick edition. This doesn't happen to me. Instead, I get

```js
const mapStateToProps = (state, ownProps) => {
    return {
        {{id:prop}}: state.{{prop}}
    };
}; // Cursor is here
```

Shouldn't you use

```js
{
    "prefix": "mapStateToProps",
    "body": [
        "const mapStateToProps = (state, ownProps) => {",
        "\treturn {",
        "\t\t${1:prop}: state.${1:prop}", // Changed here
        "\t};",
        "};"
    ],
    "description": "A Redux mapStateToProps function"
}
```

instead of your

```js
{
    "prefix": "mapStateToProps",
    "body": [
        "const mapStateToProps = (state, ownProps) => {",
        "\treturn {",
        "\t\t{{id:prop}}: state.{{prop}}",
        "\t};",
        "};"
    ],
    "description": "A Redux mapStateToProps function"
}
```

**Comment by timothymclane** [comment]
Thanks for the report! :)

I suspect this is due to recent changes with snippet support inside VS Code. I will take a look at this and attempt to resolve it. It should hopefully be an easy fix.

**Comment by Telokis** [comment]
Yes, it seems like a breaking change on the VSCode side. (Kinda odd to see that they didn't backward compat this change)
It won't be hard to change, I think.
I'd be glad to make a pull request but I don't know how to test a WIP extension

**Comment by timothymclane** [comment]
I believe I was using an undocumented API when I implemented v2.0, so it's not a surprise it broke without notice.

If you want to spend time figuring out how to make it work, you're more than welcome to, but I should be able to knock it out relatively easily once I'm off company time.

**Comment by Telokis** [comment]
I'll let you handle the changes, then.
Would you mind updating the README.md with a **Contributing** section redirecting to the official VSCode extensions documentation?
At first look, I feel very confused by the `client`/`server` directories. What does it even mean?

**Comment by timothymclane** [comment]
Yeah, I can do that.

This originally started off as a basic snippets project with some static files, but I wanted to support some super basic style options, like semicolons vs no semicolons based on a user setting. In order to do that, I implemented a language server + client that runs inside VS Code. That makes this significantly more complicated than most snippets plugins, and requires the two differing processes that run within VS Code.

I don't necessarily think it was the best thing to do (it's definitely not the most resource-efficient), but it was the only solution I could find at the time. It was also kind of fun to play with, so that's what I did.

I think I used an example project as a guide. I'll find the repo and share it. Hopefully that will give more context.

**Comment by Telokis** [comment]
Alright, thanks for the explanation, I have a better understanding I think.
I noticed some other extensions achieve this by... Having twice the "same" extension. One with semi and one without.
Btw, since you choose the "config" route, what about handling single vs double quotes?
And, wouldn't it be easier to maintain if you had only one file and *auto* generation of semi if needed?

**Comment by timothymclane** [comment]
I haven't seen those. That might be a better solution. I'd have to look.

This has really been an as-I-have-time project, and I haven't had a lot of time. Plus I've moved toward doing a lot more stuff with C#/.NET/F# + Fable rather than raw ES2015+, especially at work. Out of sight, out of mind.

Yes, it would absolutely be better to auto generate the semicolons, and handle single vs double quotes. I was trying to get an MVP/something that was Good Enough™ and functioned rather than messing around with all of that. Start with a skateboard, as they say. I talked a little bit about the conversion from 1.x to 2.x on [my (insufficiently updated) blog](http://www.timothy.codes/2016/11/28/react-redux-es6-snippets-for-vs-code-v2-0/).

That being said, you've made good suggestions, and I would like to clean things up a bit. I just need to make some time in my side projects calendar.
